### ISSUE TITLE
java.lang.StackOverflowError: stack size 8MB

### ISSUE THREAD

**Issue by mm46468648** [Gavin-ZYX/StickyDecoration#34]
at com.gavin.com.library.PowerfulStickyDecoration.getGroupName(PowerfulStickyDecoration.java:170)
	at com.gavin.com.library.BaseDecoration.isFirstInGroup(BaseDecoration.java:105)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:194)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)
	at com.gavin.com.library.BaseDecoration.getFirstInGroup(BaseDecoration.java:197)

**Comment by chengzhijun0706** [comment]
我也遇到了同样的问题，有解决的方案么

**Comment by Gavin-ZYX** [comment]
谢谢反馈，我周末处理一下
