### ISSUE TITLE
请问在列表数据为空时候和删除列表数据刷新两种情况下会报错

### ISSUE THREAD

**Issue by hyr0318** [Gavin-ZYX/StickyDecoration#35]
第一种报错：
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                       at android.graphics.Canvas.drawText(Canvas.java:1667)
                                                                                       at com.xiaobu121.xiaobu.xiaobu_android.widgets.stickyDecoration.StickyDecoration.drawDecoration(StickyDecoration.java:100)
                                                                                       at com.xiaobu121.xiaobu.xiaobu_android.widgets.stickyDecoration.StickyDecoration.onDrawOver(StickyDecoration.java:67)

第二种报错：
 UncaughtException detected: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
                                                                                     at java.util.ArrayList.get(ArrayList.java:413)
                                                                                     at com.xiaobu121.xiaobu.xiaobu_android.ui.fragment.UserStepFragment$1.getGroupName(UserStepFragment.java:121)

**Comment by Gavin-ZYX** [comment]
感谢反馈，我周末处理

**Comment by Gavin-ZYX** [comment]
如果数据清空的话，是没有item的，里面这些应该也是不会被调用到的。
不知道你的具体情况是什么样的？
